/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.math.BigDecimal;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import server.constants.Constants;

/**
 *
 * @author devtry
 */
public class frmManageStudent extends javax.swing.JFrame {
    private DatagramSocket client;
    private int port;
    private InetAddress addr;
    /**
     * Creates new form frmManageStudent
     */
    public frmManageStudent() {
        initComponents();
    }
    
    public frmManageStudent(InetAddress addr, int port) {
        this.addr = addr;
        this.port = port;
        
        initComponents();
        getInitValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnInputMark = new javax.swing.JButton();
        btnInputStudent = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSinhVien = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnThongTinSinhVien = new javax.swing.JMenuItem();
        mnDiem = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách sinh viên");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Tìm kiếm");

        btnTim.setText("Tìm");

        btnInputMark.setText("Điểm");
        btnInputMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputMarkActionPerformed(evt);
            }
        });

        btnInputStudent.setText("Sinh viên");
        btnInputStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnTim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 582, Short.MAX_VALUE)
                .addComponent(btnInputStudent)
                .addGap(33, 33, 33)
                .addComponent(btnInputMark)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(btnInputMark)
                    .addComponent(btnInputStudent))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lstSinhVien.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstSinhVien);

        jMenu1.setText("Quản lý sinh viên");

        mnThongTinSinhVien.setText("Thông tin sinh viên");
        mnThongTinSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThongTinSinhVienActionPerformed(evt);
            }
        });
        jMenu1.add(mnThongTinSinhVien);

        mnDiem.setText("Điểm");
        mnDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiemActionPerformed(evt);
            }
        });
        jMenu1.add(mnDiem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnThongTinSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThongTinSinhVienActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        frmNewStudent obj = new frmNewStudent(this,addr,port);
        obj.setVisible(true);
    }//GEN-LAST:event_mnThongTinSinhVienActionPerformed

    private void mnDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiemActionPerformed
        // TODO add your handling code here:
                this.dispose();
//                    frmNewStudent obj = new frmNewStudent(addr,port);
                    frmInputMark obj = new frmInputMark(this,addr,port);
                    obj.setVisible(true);
    }//GEN-LAST:event_mnDiemActionPerformed

    private void btnInputMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputMarkActionPerformed
        // TODO add your handling code here:
        this.dispose();
//                    frmNewStudent obj = new frmNewStudent(addr,port);
        frmInputMark obj = new frmInputMark(this,addr,port);
        obj.setVisible(true);
    }//GEN-LAST:event_btnInputMarkActionPerformed

    private void btnInputStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputStudentActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmNewStudent obj = new frmNewStudent(this,addr,port);
        obj.setVisible(true);
    }//GEN-LAST:event_btnInputStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManageStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputMark;
    private javax.swing.JButton btnInputStudent;
    private javax.swing.JButton btnTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstSinhVien;
    private javax.swing.JMenuItem mnDiem;
    private javax.swing.JMenuItem mnThongTinSinhVien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void getInitValue() {
        String[] sv = getListStudents();
        
        DefaultListModel dm = new DefaultListModel();

            if (sv.length > 0) {
            for (int i = 0; i < sv.length; i++) {
                String kq = null;
                String[] arr = sv[i].split(",");
                int tt = i + 1;
                System.out.println("len" + arr.length);
                String[] diems = null;
                if (arr.length > 3) {
                    diems = arr[3].split("&");
                }

                if (diems != null) {
                    float avg = (Float.parseFloat( diems[0]) + Float.parseFloat(diems[1]) + Float.parseFloat(diems[2]))/3;
                    float roundAvg = BigDecimal.valueOf(avg)
                         .setScale(2, BigDecimal.ROUND_HALF_DOWN)
                         .floatValue();
                    kq = "" + tt + ", MSSV: " + arr[0] + "       ,Họ tên: " + arr[1] + " " + arr[2] + "       ,Toán: " + diems[0] + "       ,Văn: " + diems[1] + "       ,Anh: " + diems[2]+ "       ,TB: " + roundAvg;
                } else {
                    kq = "" + tt + ", MSSV: " + arr[0] + "       ,Họ tên: " + arr[1] + " " + arr[2];
                }

                dm.addElement(kq);
            }
                
            } else {
                String kq = "Không có sinh viên !!!!";
                dm.addElement(kq);
            }

            this.lstSinhVien.setModel(dm);
            this.validate();
    }
    
    private String[] getListStudents (){
        String result = null;
        try {
            client = new DatagramSocket();
            //Tạo dữ liệu(group of bytes) cho gói tin nhận và gói tin gủi
            byte[] sendData;
            byte[] receiveData = new byte[65507];

            //get text
            String action = String.valueOf(Constants.GET_STUDENTS_WITH_MARKS);
            sendData = action.getBytes();
            DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, addr, port);
            client.send(sendPacket);

            byte[] buffer = new byte[65507]; //capacity of data package 65535 - (7 bytes header of UDP)

            //received result from server
            DatagramPacket receivePacket = new DatagramPacket(buffer, buffer.length);
            client.receive(receivePacket);

            //display data on screen
            result = new String(receivePacket.getData()).trim();
//            System.out.println("list std: " + result);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return result.split("#");
    }
}
